create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  tool_name text,
  email text,
  content text,
  type text default 'text',
  metadata jsonb,
  created_at timestamp with time zone default now()
);

-- Index for faster querying by room
create index if not exists idx_messages_room_id on messages(room_id);
