create table instagram_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  status text default 'pending',
  last_checked timestamp with time zone,
  created_at timestamp with time zone default now()
);
